### ISSUE TITLE
pm.units.show() function not working

### ISSUE THREAD

**Issue by DerickBO** [chmarti1/PYroMat#30] opened 2021-11-11 14:56 UTC
Dear Christopher,  when trying to use the `pm.units.show() ` function, the function is not working correctly, returning an `AttributeError: 'dict' object has no attribute 'iteritems'` Regards.

**Comment by chmarti1** [comment] 2021-11-11 15:33
Confirmed.  This is an old piece of code that is left over from when I mostly developed in Python 2.  It would appear that very few of us use the show() function for the bug to have survived so long.  Since this isn't critical to function, I may wait a week or so before I push out an update.

**Comment by chmarti1** [comment] 2022-07-08 14:44
This is now fixed with the v2.2.0 push.  Thanks for patience, and thanks for helping us improve!

**Closed by chmarti1** 2022-07-08 14:44 UTC
Labels: bug, resolved
